//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEighhtBall")]
public interface IEighhtBall
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEighhtBall/ObtainAnswerToQuestion", ReplyAction="http://tempuri.org/IEighhtBall/ObtainAnswerToQuestionResponse")]
    string ObtainAnswerToQuestion(string userQuestion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEighhtBall/ObtainAnswerToQuestion", ReplyAction="http://tempuri.org/IEighhtBall/ObtainAnswerToQuestionResponse")]
    System.Threading.Tasks.Task<string> ObtainAnswerToQuestionAsync(string userQuestion);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEighhtBallChannel : IEighhtBall, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EighhtBallClient : System.ServiceModel.ClientBase<IEighhtBall>, IEighhtBall
{
    
    public EighhtBallClient()
    {
    }
    
    public EighhtBallClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EighhtBallClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EighhtBallClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EighhtBallClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string ObtainAnswerToQuestion(string userQuestion)
    {
        return base.Channel.ObtainAnswerToQuestion(userQuestion);
    }
    
    public System.Threading.Tasks.Task<string> ObtainAnswerToQuestionAsync(string userQuestion)
    {
        return base.Channel.ObtainAnswerToQuestionAsync(userQuestion);
    }
}
